feature/SKED-2317: Crop on big image IE bug in profile/general
skedify/web-app-dependency-vanilla-image-cropper pull request #1
Opened 2017-05-10 11:55 UTC by gevalo1

2017-05-10 14:00 UTC, ThomasSimoens requested changes
See PR file comments

2017-05-10 14:00 UTC, ThomasSimoens commented on src/js/components/handles/index.js
> +            const toggle_event = createEvent('source:dimensions');
You can still keep this a one liner, I think `scope.$$parent.dispatchEvent(createEvent('source:dimensions'))` is clear enough (also check other usage)

2017-05-10 14:00 UTC, ThomasSimoens commented on gulpfile.js
> +            // https://www.npmjs.com/package/gulp-scss-lint#install
I wouldn't commit this change, linting should still be done, but can be disabled if desired...

2017-05-10 14:00 UTC, ThomasSimoens commented on src/js/utils/CreateEvent.js
> +export function createEvent(event_type) {
While this `toggle_event` variable recycle will work (and is sometimes preferred), I think a more direct approach would be more readable; try to return the `CustomEvent` immediately, when that fails instantiate the new `const toggle_event`.

I also think the explicit variables (`can_bubble`, etc.) aren't really necessary; the method signature of `initCustomEvent` should explain what the arguments mean. Maybe also add some documentation why you are trying the other deprecated approach (`initCustomEvent`, I assume IE support?)

Good idea to move this to a util!

2017-05-11 09:16 UTC, gevalo1 commented
Note: the 'UnnecessaryParentReference' rule used in the old .scss-lint.yml file doesn't seem to be supported by sass-lint. (yet)
Docs for this rule: https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#unnecessaryparentreference

2017-05-11 09:31 UTC, gevalo1 commented on src/js/utils/CreateEvent.js
> +export function createEvent(event_type) {
We could use the polyfill as specified here: https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill

This way the CreateEvent function could be removed entirely.

2017-05-11 16:10 UTC, closed without merging